server_port: 6543

mcp_servers:
  - name: "filesystem"
    command: "npx"
    args: ["@modelcontextprotocol/server-filesystem", "/path/to/your/directory"]
    clients:
      claude_code: true
      gemini_cli: false

  - name: "context7"
    http_url: "https://mcp.context7.com/mcp"
    headers:
      CONTEXT7_API_KEY: "ADD_YOUR_API_KEY"
    clients:
      claude_code: false
      gemini_cli: false

clients:
  - name: "claude_code"
    config_path: "~/.claude.json"
  - name: "gemini_cli"
    config_path: "~/.gemini/settings.json"
