server_port: 6543

mcp_servers:
  - name: "filesystem"
    command: "npx"
    args: ["@modelcontextprotocol/server-filesystem", "/path/to/your/directory"]
    enabled_globally: true
    clients:
      claude_code: true
      gemini_cli: false

  - name: "git"
    command: "npx"
    args: ["@modelcontextprotocol/server-git", "--repository", "/path/to/your/repo"]
    enabled_globally: false
    clients:
      claude_code: true
      gemini_cli: true

  - name: "postgres"
    command: "npx"
    args: ["@modelcontextprotocol/server-postgres"]
    env:
      POSTGRES_URL: "postgresql://localhost:5432/mydb"
    enabled_globally: false
    clients:
      claude_code: false
      gemini_cli: true

clients:
  - name: "claude_code"
    config_path: "~/.claude/settings.json"
  - name: "gemini_cli"
    config_path: "~/.gemini/settings.json"
